---
- name: 'Get ISO 8601 Date'
  setup:
    gather_subset: '!all'
  register: localhost_ansible_facts
  run_once: true
  delegate_to: localhost

- name: 'Set Date Variable'
  set_fact:
    date: "{{ localhost_ansible_facts.ansible_facts.ansible_date_time.iso8601 }}"
  run_once: true
  delegate_to: localhost

- name: 'Set Backup File Name Variable'
  set_fact:
    backup_filename: "{{ ansible_network_os }}-config_{{ date }}"
  delegate_to: localhost

- name: 'Ensure Backup Directories Exist'
  file:
    path: "{{ backup_dir }}"
    state: directory
  delegate_to: localhost

- name: 'Include Junos Backup Tasks'
  include_tasks: backup_junos.yml
  when: ansible_network_os == 'junos'

- name: 'Include Cisco IOS Backup Tasks'
  include_tasks: backup_ios.yml
  when: ansible_network_os == 'ios'

- name: 'Include Cisco NX-OS Backup Tasks'
  include_tasks: backup_nxos.yml
  when: ansible_network_os == 'nxos'

- name: 'Include Palo Alto Networks PAN-OS Backup Tasks'
  include_tasks: backup_panos.yml
  when: ansible_network_os == 'panos'
